name: Build PR and Main

permissions:
  contents: write
  pull-requests: write
  issues: write
  statuses: write
  packages: write

on:
  pull_request:
    paths:
      - 'containers/**'
  push:
    paths:
      - 'containers/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to use'
        required: true
        default: 'main'
      deploy:
        description: 'Deploy images to GHCR'
        required: false
        default: 'false'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - name: spellcarver-python311
            dockerfile: ./containers/python311/Dockerfile
            context: ./containers/python311/
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.app.context }}
          file: ${{ matrix.app.dockerfile }}
          # Only push if this is a push to main or if deploy input is true
          push: ${{ github.event_name == 'push' || github.event.inputs.deploy == 'true' }}
          tags: |
            ghcr.io/the-mines/spellcarver-base-images/${{ matrix.app.name }}:${{matrix.app.env}}-${{ env.SHORT_SHA }}
        continue-on-error: true